[build]
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/admin-login-new.html"
  status = 200

[[redirects]]
  from = "/admin-login"
  to = "/admin-login-new.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/admin-dashboard-new.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"